export enum TranslationKeys {
  welcome = 'welcome',
  features = 'features',
  about = 'about',
  searchPlaceholder = 'searchPlaceholder',
  back = 'back',
  favorites = 'favorites',
  noFavorites = 'noFavorites',
  goToWelcome = 'goToWelcome',
  tabs = 'tabs',
  main = 'main',
  details = 'details',
  promptToAction = 'promptToAction',
  abstractDescription = 'abstractDescription',
  includedFeatures = 'includedFeatures',
  feature1 = 'feature1',
  feature2 = 'feature2',
  feature3 = 'feature3',
  feature4 = 'feature4',
  feature5 = 'feature5',
  feature6 = 'feature6',
  feature7 = 'feature7',
  feature8 = 'feature8',
  descriptionSummary = 'descriptionSummary',
  darkMode = 'darkMode',
}
